### ISSUE TITLE
[Feature request] Provide changelog

### ISSUE THREAD

**Issue by vlatkoB** [fpco/lts-haskell#10]
Hi,
It would be nice if we could see which packages got upgraded from last `LTS`.

br.
vlatko

**Comment by DanBurton** [comment]
:+1: This is something I'd also like to see. I believe @snoyberg already wrote a diff algorithm for this?

**Comment by snoyberg** [comment]
The stackage-curator package can diff any two build plans.

**Comment by vlatkoB** [comment]
I thought more of a link (or a section) on LTS web page to easily browse the upgrades between the last and current LTS. The diff to be part of LTS release.

**Comment by bergmark** [comment]
I'd like this for nightlies as well, esp to see newly added packages.

**Comment by bergmark** [comment]
`stackage-curator diff` is exactly what i wanted!

**Comment by snoyberg** [comment]
I'd be happy to accept a PR to add this functionality to stackage-server, but I don't have time to implement it myself, especially since I already have the functionality I need in `stackage-curator`.

**Comment by vlatkoB** [comment]
Played a little bit and added four switches to `stackage-curator diff`. 
Now it can fetch lts files from github and show differences only, in colour to console or as html.
It is [here](https://github.com/vlatkoB/stackage-curator).
If you find any of these features interesting, I can make a PR.

**Comment by snoyberg** [comment]
A PR for something like that sounds great. I haven't yet reviewed the code
or tested out the feature, but I can't imagine it's going to break anything
since the `diff` code lives all by itself.

**Comment by vlatkoB** [comment]
[Done](https://github.com/fpco/stackage-curator/pull/5). Those are additions only. Standard workflow didn't change, to see any change, you must use a switch.
