### ISSUE TITLE
Include newer warp version in LTS 10

### ISSUE THREAD

**Issue by snoyberg** [fpco/lts-haskell#101]
I'm not sure why, but there is currently an upper bound in LTS 10 preventing warp >= 3.2.15 from being included. (For all I know, I'm the one who added it.) The version currently included has a space leak, see https://github.com/yesodweb/wai/issues/676. For the next LTS 10 release, can we relax that upper bound? CC @kazu-yamamoto @huseyinyilmaz

**Comment by bergmark** [comment]
There is a valid plan at least using
```
$ CONSTRAINTS='--constraint "warp>=3.2.15" --constraint "markup<4.0.4"' ./build.sh lts-10.9
```

**Comment by DanBurton** [comment]
There may be a build or test failure. I don't quite recall. It's worth giving it another try regardless.

**Comment by DanBurton** [comment]
The benchmark has a build failure. https://github.com/yesodweb/wai/issues/681

I'll just mark the bench failure as expected.

**Comment by bergmark** [comment]
This was fixed.
