### ISSUE TITLE
add aeson-picker into LTS-10

### ISSUE THREAD

**Issue by ozzzzz** [fpco/lts-haskell#102]
Checklist for adding a package:
- [+] specified the Stackage LTS version in the summary
- [+] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by alexeyzab** [comment]
Added to lts-10.10. https://www.stackage.org/lts-10.10/package/aeson-picker-0.1.0.4
