### ISSUE TITLE
Please re-add pandoc and pandoc-citeproc.

### ISSUE THREAD

**Issue by jgm** [fpco/lts-haskell#106]
I have relaxed the upper-bound on http-types on Hackage for pandoc 2.1.2.
I have submitted a PR re-adding these packages to nightly.

**Comment by DanBurton** [comment]
Given that your quick turnaround got them back into the nightly build already, these package will also make it into the initial release of LTS 11. Thanks!

**Comment by jgm** [comment]
Excellent, thanks!

+++ Dan Burton [Mar 12 18 05:22 ]:
