### ISSUE TITLE
Please add bsb-http-chunked to LTS-10 and LTS-11

### ISSUE THREAD

**Issue by sjakobi** [fpco/lts-haskell#108]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
Added to lts 10 https://www.stackage.org/lts-10.10/package/bsb-http-chunked-0.0.0.2
Added to lts 11 https://www.stackage.org/lts-11.1/package/bsb-http-chunked-0.0.0.2

**Comment by sjakobi** [comment]
Thanks! :)
