### ISSUE TITLE
add: elm-export-persistent-0.2.0 to lts-11

### ISSUE THREAD

**Issue by jb55** [fpco/lts-haskell#109]
Checklist for adding a package:

- [x] specified the Stackage LTS version in the summary

- [x] On your own machine, in a new directory, you have succesfully run the
following set of commands (replace `elm-export-persistent` with the name of
the package that is submitted, `0.2.0` is the version of the package you want
to get into the LTS series, and `11` is the desired LTS series):

      stack unpack elm-export-persistent-0.2.0
      cd elm-export-persistent-0.2.0
      stack init --resolver lts-11
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
Added to lts 11 https://www.stackage.org/lts-11.1/package/elm-export-persistent-0.2.0
