### ISSUE TITLE
lts-3.2 upper bounds introduced

### ISSUE THREAD

**Issue by snoyberg** [fpco/lts-haskell#11]
The following bounds issues are introduced with lts-3.2:

hspec-expectations-0.7.2 depended on by:
- hspec-2.1.10 (==0.7.1.*). Simon Hengel <sol@typeful.net>. @hspec
- hspec-core-2.1.10 (==0.7.1.*). No maintainer. @hspec

microlens-0.2.0.0 depended on by:
- microlens-mtl-0.1.4.1 (>=0.3.1 && < 0.4). Artyom <yom@artyom.me>. @aelve

tagged-0.8.1 depended on by:
- tasty-hspec-1.1.1 (==0.7.*). Mitchell Rosen <mitchellwrosen@gmail.com. @mitchellwrosen

**Comment by snoyberg** [comment]
Adding in the following constraints to compensate:

```
hspec-expectations < 0.7.2
microlens-mtl < 0.1.4.1
tasty-hspec < 1.1.1
```

**Comment by mitchellwrosen** [comment]
I just uploaded tasty-hspec-1.1.2 which has relaxed the tagged dependency, and should compile against hspec-2.2.0 as well.
