### ISSUE TITLE
Please add conduit-algorithms to LTS-11

### ISSUE THREAD

**Issue by luispedro** [fpco/lts-haskell#110]
The package was in LTS-10 and has now been updated to work with conduit-1.3 and LTS-11.0

https://travis-ci.org/luispedro/conduit-algorithms/builds/352778821

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
Added to LTS 11 https://www.stackage.org/lts-11.1/package/conduit-algorithms-0.0.8.0
