### ISSUE TITLE
Add dhall to lts-11.0

### ISSUE THREAD

**Issue by Gabriel439** [fpco/lts-haskell#111]
For context, see: https://github.com/fpco/stackage/issues/3143#event-1514806120

I tested the latest version of `dhall` (`dhall-1.11.1`) against `lts-11.0`

Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
Added (only `dhall`, not its revdeps) to LTS 11 https://www.stackage.org/lts-11.1/package/dhall-1.11.1

The revdeps could probably also be added, upon request.
