### ISSUE TITLE
Add yesod-gitrev to LTS 11

### ISSUE THREAD

**Issue by DanBurton** [fpco/lts-haskell#112]
(With no urgency.)

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
The build script was acting weird, not selecting the latest version of this package, so this got left off of lts-11.1. It can wait until lts-11.2.

**Comment by jkachmar** [comment]
`yesod-gitrev` is now in LTS 11.2: https://www.stackage.org/lts-11.2/package/yesod-gitrev-0.2.0.0
