### ISSUE TITLE
01-index.tar: hGetBuf: hardware fault

### ISSUE THREAD

**Issue by Momentum93** [fpco/lts-haskell#113]
When i run various stack commands (e.g. stack upgrade, stack build, etc.) I get the following error:

```
$stack ...
Unable to load cabal files for snapshot
(...)
/home/thomas/.stack/indices/Hackage/01-index.tar: hGetBuf: hardware fault (I/O error)

```

**Comment by juhp** [comment]
Please file against stack: https://github.com/commercialhaskell/stack/issues

**Comment by snoyberg** [comment]
Closing as it belongs against Stack. But note that the error message strongly implies a hardware failure is at play.
