### ISSUE TITLE
Add cisco-spark-api to lts-11

### ISSUE THREAD

**Issue by nshimaza** [fpco/lts-haskell#114]
It was removed due to nshimaza/cisco-spark-api#1
The latest cisco-spark-api-0.1.0.2 was tested against lts-11.1.

Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by jkachmar** [comment]
`cisco-spark-api` is now in LTS 11.2: https://www.stackage.org/lts-11.2/package/cisco-spark-api-0.1.0.2
