### ISSUE TITLE
Add `dhall-json` to LTS 11.1

### ISSUE THREAD

**Issue by Gabriel439** [fpco/lts-haskell#115]
I'm not sure if I'm supposed to specify the LTS minor version or not, but I tested against LTS 11.1

I don't need to add other `dhall` reverse dependencies to LTS 11.*.  This should be the last LTS-11-related request

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
> I'm not sure if I'm supposed to specify the LTS minor version or not

Generally not. Since published snapshots are immutable, we won't actually alter LTS 11.1. Instead, we will attempt to include your package in future minor version bumps of LTS 11 (in this case, LTS 11.2 and on).

> I tested against LTS 11.1

Excellent! It is quite likely, then, that we will be able to include `dhall-json` in lts-11.2 and onwards.

**Comment by Gabriel439** [comment]
I should probably also clarify that the testing I did was for `dhall-json-1.0.12`.  I will probably cut a new release of `dhall-json` in a few days but I don't expect that newer release to make it in to LTS-11

**Comment by jkachmar** [comment]
`dhall-json` is now in LTS 11.2: https://www.stackage.org/lts-11.2/package/dhall-json-1.0.13

**Comment by Gabriel439** [comment]
Thank you!
