### ISSUE TITLE
Add Hakyll to lts-11

### ISSUE THREAD

**Issue by jaspervdj** [fpco/lts-haskell#117]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by jkachmar** [comment]
`hakyll` is now in LTS 11.2: https://www.stackage.org/lts-11.2/package/hakyll-4.12.0.1
