### ISSUE TITLE
Add hasty-hamiltonian and declarative to lts-11

### ISSUE THREAD

**Issue by jtobin** [fpco/lts-haskell#118]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

(Note: the latest declarative relies on the latest hasty-hamiltonian, so I needed to add --solver while initting)

Resolves jtobin/hasty-hamiltonian#2.

**Comment by jkachmar** [comment]
`hasty-hamiltonian` and `declarative` are now in LTS 11.2: https://www.stackage.org/lts-11.2/package/hasty-hamiltonian-1.3.2 and https://www.stackage.org/lts-11.2/package/declarative-0.5.2 respectively

**Comment by jtobin** [comment]
Thanks Joe!
