### ISSUE TITLE
Add beam-core, beam-migrate, and beam-sqlite to LTS 11

### ISSUE THREAD

**Issue by tathougies** [fpco/lts-haskell#120]
I just added these to stackage nightly. I've been building these three packages with LTS 11, and would like to have them included.

As an aside, can I get `beam-postgres` into LTS 11, even if it won't build in nightly, due to a missing `postgresql-simple` dependency?

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by mihaimaruseac** [comment]
> As an aside, can I get `beam-postgres` into LTS 11, even if it won't build in nightly, due to a missing `postgresql-simple` dependency?

I see the dependency is in LTS, so I think it should be ok. I'll do the addition late Friday.

**Comment by tathougies** [comment]
Will I need to open up an issue to add `beam-postgres` to build-constraints in the main stackage repository?

Thanks for the help! I'm new to this

**Comment by mihaimaruseac** [comment]
I don't know at the moment, will test Friday :)

**Comment by mihaimaruseac** [comment]
I'm adding all 3 packages into the LTS now, you don't need to add it to the build-constraints from what I see.
