### ISSUE TITLE
Please add minio-hs-1.0.0 to lts-11

### ISSUE THREAD

**Issue by donatello** [fpco/lts-haskell#122]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by donatello** [comment]
I had to specify `--force` in the `stack init` in the check list above to get it work as the package already includes a stack.yaml. Should this not be be done?

**Comment by alexeyzab** [comment]
Added to `lts-11.7`: https://www.stackage.org/lts-11.7/package/minio-hs-1.0.0
