### ISSUE TITLE
Please add rio to LTS 11

### ISSUE THREAD

**Issue by snoyberg** [fpco/lts-haskell#125]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by DanBurton** [comment]
Added. https://www.stackage.org/lts-11.9/package/rio-0.1.2.0

**Comment by snoyberg** [comment]
Thanks!
