### ISSUE TITLE
add darcs to lts-4

### ISSUE THREAD

**Issue by simonmichael** [fpco/lts-haskell#19]
We'd like to have these added to lts-4:

- darcs
- regex-compat-tdfa

**Comment by DanBurton** [comment]
LTS 4 is being discontinued prematurely. (https://unknownparallel.wordpress.com/2016/01/18/stackage-is-reverting-to-aeson-0-9/)

I'll see what I can do to get these into LTS 5 (estimated release 2016-01-24).

**Comment by juhp** [comment]
darcs is already in Stackage Nightly so I guess it should land in lts-5 when it comes out soon.

Does that work for you, Simon?

**Comment by simonmichael** [comment]
Ok, that's good. Thanks!
