### ISSUE TITLE
Add fail-4.9.0.0 to LTS 5

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#21]
I already tripped up a bunch of times because I wanted to build aeson-0.11.0.0 with LTS 5, which currently needs fail as an extra-dep.

ping @hvr (no action necessary from you)

**Comment by snoyberg** [comment]
I'm trying to add this now to LTS 5.6.

**Comment by hvr** [comment]
I'm slightly confused... according to https://www.stackage.org/package/fail it's already part of LTS 5.5?

**Comment by snoyberg** [comment]
Thanks, good catch. Then my actions for 5.6 will do absolutely nothing :). Closing this as already implemented.

**Comment by bergmark** [comment]
I forgot to close this, sorry.
