### ISSUE TITLE
Include the LTS release frequency in the README

### ISSUE THREAD

**Issue by ndmitchell** [fpco/lts-haskell#22]
Weekly? Nightly? Monthly? It's the one question I wanted to know, and I still don't...

**Comment by snoyberg** [comment]
Weekly. I'm not at my computer right now, would you be able to send a PR with an update? Thanks for catching this

**Comment by ndmitchell** [comment]
Is it on a specific schedule? Say every Monday or other specific day of the week?

**Comment by snoyberg** [comment]
We've typically been running them on Sundays, though sometimes the build
takes a bit of time to succeed so it _could_ bleed into Monday or Tuesday.

**Comment by ndmitchell** [comment]
I started working on a pull request, but then realised there is even more information I don't know. I think the first paragraph should read (I guessed at 3 months since I have no real idea):

----------

LTS (Long Term Support) Haskell is a curated set of packages, a more stable companion to Stackage Nightly.

* Minor 0.1 increments to LTS are produced weekly, typically on Sunday, containing only API compatible changes to existing packages.
* Major 1.0 increments to LTS are produced every 3 months containing API changes, additional packages, and occasional package removals.
* In contrast, Stackage Nightly releases are produced nightly containing API changes and package changes.

**Comment by snoyberg** [comment]
We don't have a fixed timeline on major version bumps. We've been targeting between 3-6 months until now, but it fluctuates based on factors like discovery of bugs and GHC releases.

**Comment by bergmark** [comment]
Also note that minor releases can add new packages as well.

**Comment by snoyberg** [comment]
I'll take over on making these changes, I also have a new policy change to include.
