### ISSUE TITLE
I would like point-octree added to lts-6

### ISSUE THREAD

**Issue by mlitchard** [fpco/lts-haskell#23]

**Comment by DanBurton** [comment]
Sorry, I forgot about this while working on lts-6.8. I'll try to get it added into lts-6.9 which is expected around Sunday/Monday.

**Comment by mlitchard** [comment]
No worries.

**Comment by DanBurton** [comment]
Done: https://www.stackage.org/lts-6.9/package/point-octree-0.5.5.3
