### ISSUE TITLE
hspec 2.2.4 in LTS 7

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#27]
Because of fpco/stackage#1902 i had to add a `hspec<2.2.4` constraint for lts-7.1. I'd like to have that constraint dropped when the nightly bound is dropped.

**Comment by DanBurton** [comment]
The constraint has been lifted in nightly builds by skipping point-octree's test suite. @snoyberg can we add a `--skip-tests` feature to stackage-curator so that we can skip point-octree's test suite for the next lts?

**Comment by snoyberg** [comment]
The approach I'd rather try is:

* Add the CONSTRAINTS
* This will generate a build-plan.yaml file, which will fail the check
* Manually edit that build-plan.yaml to skip tests where needed
* Rerun with NOPLAN=1

The reason for this is that adding flags for all of the different possibilities is quickly going to get out of control (I think, could be wrong). Anyway, I'll try to

**Comment by snoyberg** [comment]
OK, this is now resolved: https://www.stackage.org/diff/lts-7.6/lts-7.7
