### ISSUE TITLE
Add quickbench to LTS 7

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#29]
Ping @simonmichael

**Comment by simonmichael** [comment]
Hi @bergmark, how do we get quickbench into LTS ?

**Comment by bergmark** [comment]
This ticket is a reminder for @DanBurton to add it to the next snapshot which should be this weekend.

**Comment by DanBurton** [comment]
lts-7.6 has been published, including quickbench-1.0

https://www.stackage.org/lts-7.6/package/quickbench-1.0

**Comment by simonmichael** [comment]
Thanks!
