### ISSUE TITLE
hledger 1.0.*

### ISSUE THREAD

**Issue by DanBurton** [fpco/lts-haskell#30]
@simonmichael requests a major version bump of hledger in the next LTS 7 release.

**Comment by DanBurton** [comment]
Not just hledger, but also any packages prefixed with `hledger`

**Comment by DanBurton** [comment]
@simonmichael hledger 1.0.1, hledger-lib 1.0.1, and hledger-interest 1.4.4 are now in LTS 7.6.

I didn't realize that the following were not in the lts build plan, do you want us to try and add them for the next lts release?

* hledger-ui
* hledger-web
* hledger-api

**Comment by simonmichael** [comment]
Thanks Dan! Sure, if not too much hassle it would be good to have the full set there. 

I realised that being in LTS doesn't really avoid the need to specify a resolver in install instructions. So for now I'm recommending `--resolver nightly` and this seems fine.

**Comment by DanBurton** [comment]
Right. In order to install, one must either 

* have the appropriate resolver set in `~/.stack/global-project/stack.yaml`, and not be in a project directory
* be in a project direcotry with the appropriate resolver specified in that project's `stack.yaml`
* specify the appropriate resolver on the command line

Stack is less tuned for global installation of executables, and more tuned for project-based installation of dependencies.

**Comment by bergmark** [comment]
`--resolver lts-7` is safer and should stay working while just `lts` or `nightly` might break at some point in the future.

**Comment by simonmichael** [comment]
Thanks. There's a tension between safety ("this command works forever") and usability ("this command is short, easy to remember, does not change, does not needlessly compile a lot of essentially-the-same software"). `--resolver lts-MAJOR` sounds like the best compromise if all your packages are in LTS.

**Comment by snoyberg** [comment]
Closing this so we can focus any discussion on fpco/stackage#2034
