### ISSUE TITLE
Add line to LTS 7

### ISSUE THREAD

**Issue by noraesae** [fpco/lts-haskell#31]
- Hackage: https://hackage.haskell.org/package/line
- GH repo: https://github.com/noraesae/line

I have also considered adding it in the nightly, but it has `wreq` as its dependency and `wreq` is missing in the nightly. I may try after `wreq` is included in the stackage again.

If there is something I missed, please let me know.

Thanks in advance.

**Comment by juhp** [comment]
Thanks, added to lts-7.12.

https://www.stackage.org/package/line
