### ISSUE TITLE
Include tls-1.3.9 in next LTS 6 and 7

### ISSUE THREAD

**Issue by snoyberg** [fpco/lts-haskell#33]
I believe I put in the upper bound on tls due to it pulling in a new version of cryptonite. However, there is a significant bug fix for Google domain names in tls-1.3.9, and cryptonite doesn't follow PVP versioning rules anyway, so I propose allowing this exception for the next LTS snapshots we produce.

Relevant issues:

* https://github.com/vincenthz/hs-tls/issues/169
* https://github.com/snoyberg/http-client/issues/236

**Comment by DanBurton** [comment]
👍 We've bumped cryptonite in the past, and I'm sure we'll do it again. As long as it doesn't break anything that's already in the LTS series (read: builds and tests continue to pass), then I say go for it.

**Comment by juhp** [comment]
@lwm can you include this in the next lts7 build?
IIRC you just need to use `CONSTRAINTS='--constraint "tls >= 1.3.9"'` to pull it in.

**Comment by lwm** [comment]
Yep @juhp, on my todo list for next lts7 :+1:

**Comment by snoyberg** [comment]
I'm running the LTS-6 build shortly, I'm going to close this out though since it made it into LTS 7.
