### ISSUE TITLE
Include rot13

### ISSUE THREAD

**Issue by kvanberendonck** [fpco/lts-haskell#35]
Could you walk me through what I need to do to have this added.

Hackage: http://hackage.haskell.org/package/rot13

Thanks

**Comment by juhp** [comment]
Could you add it to Stackage Nightly first?

https://github.com/fpco/stackage/blob/master/MAINTAINERS.md

**Comment by juhp** [comment]
Adding to lts-8.2.

**Comment by kvanberendonck** [comment]
PR is stackage#2318
