### ISSUE TITLE
Add 'hasbolt' to LTS-8

### ISSUE THREAD

**Issue by zmactep** [fpco/lts-haskell#40]
Current nightly: [Stackage Nightly 2017-03-04](https://www.stackage.org/nightly-2017-03-04/package/hasbolt-0.1.1.1)
Hackage: [hasbolt-0.1.1.1](https://hackage.haskell.org/package/hasbolt-0.1.1.1)

**Comment by snoyberg** [comment]
Syncing with LTS 8.4 now.
