### ISSUE TITLE
Add groundhog to LTS 7 and 8

### ISSUE THREAD

**Issue by lykahb** [fpco/lts-haskell#41]
Groundhog was dropped from Stackage nightly because it is was not compatible with GHC 8. In the recent release that was fixed.

List of packages:
* groundhog-0.8
* groundhog-th-0.8
* groundhog-sqlite-0.8
* groundhog-postgresql-0.8
* groundhog-mysql-0.8
* groundhog-inspector-0.8

Thank you!

**Comment by bergmark** [comment]
I added this to last weeks LTSes!
