### ISSUE TITLE
please consider adding data-easy and test-invariant to lts-8.n

### ISSUE THREAD

**Issue by andrewufrank** [fpco/lts-haskell#48]
they are useful when testing. thank you!

**Comment by juhp** [comment]
We don't have a strict policy on this but I think they should really be added to Stackage Nightly first.

**Comment by juhp** [comment]
Anyway when I try to add data-easy to lts-8 I get:

QuickCheck-2.9.2 is out of bounds for:
- [ ] data-easy-0.7.0 (==2.7.*). No maintainer. @jcristovao. Used by: test-suite

base-4.9.1.0 is out of bounds for:
- [ ] data-easy-0.7.0 (>=4.6 && < 4.9). No maintainer. @jcristovao. Used by: library, test-suite

transformers-0.5.2.0 is out of bounds for:
- [ ] data-easy-0.7.0 (==0.4.*). No maintainer. @jcristovao. Used by: test-suite

**Comment by juhp** [comment]
https://www.stackage.org/lts-8.13/package/test-invariant-0.4.5.0

Please open another ticket if/when data-easy can be added.
I would probably work in an older lts.
