### ISSUE TITLE
please consider adding hgal and rdf4h to lts-8.n 

### ISSUE THREAD

**Issue by andrewufrank** [fpco/lts-haskell#49]
they are used to work with RDF/semantic web data structures
thank you!

**Comment by juhp** [comment]
> /tmp/stackage-build13/rdf4h-3.0.1$ dist/build/test-rdf4h/test-rdf4h
test-rdf4h: rdf-tests/turtle/manifest.ttl: openFile: does not exist (No such file or directory)

**Comment by juhp** [comment]
I added https://www.stackage.org/lts-8.13/package/hgal-2.0.0.2

Skipped rdf4h due to preceding comment.

**Comment by juhp** [comment]
robstewart57/rdf4h#39
