### ISSUE TITLE
please consider adding chatter, fullstop and tokenizer to lts-8.n

### ISSUE THREAD

**Issue by andrewufrank** [fpco/lts-haskell#50]
these packages are useful for processing natural language.
thank you !

**Comment by juhp** [comment]
HUnit-1.5.0.0 (Adam Bergmark <adam@bergmark.nl> @bergmark) is out of bounds for:
- [ ] fullstop-0.1.4 (==1.2.*). No maintainer.. Used by: test-suite

cereal-0.5.4.0 is out of bounds for:
- [ ] chatter-0.9.1.0 (>=0.4.0.1 && < 0.5.4.0). No maintainer. @creswick. Used by: library, executable, test-suite

**Comment by juhp** [comment]
I can't find tokenizer!

**Comment by creswick** [comment]
@juhp I suspect this is the package: https://hackage.haskell.org/package/tokenize @andrewufrank was thinking of.

I've bumped the bounds on cereal in chatter, and emailed Eric Kow about fullstop's HUnit dependency; if/when that's taken care of I'll cut a new chatter release and update this ticket.

**Comment by andrewufrank** [comment]
thank you! I am sorry for the spelling error in tokenize.
