### ISSUE TITLE
please add data-easy to nightly

### ISSUE THREAD

**Issue by andrewufrank** [fpco/lts-haskell#51]
i did not understand the policy to add first to nightly. i have switched to use it.
regarding data-easy: i see as a maintainer `jmacristovao@gmail.com` and as bounds `base (>=4.6 && <4.11)`
i only try to understand your operations  - can you point me to doc where i can see which packages I may ask to be added and why others are not. 
thank you for your work - it is very helpful to avoid `cabal hell`

**Comment by juhp** [comment]
To add to nightly please open a PR against fpco/stackage.
See https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by andrewufrank** [comment]
thank you  - i will try to follow the instructions for future additions. the document is very instructive!
