### ISSUE TITLE
add triplesec to lts-9

### ISSUE THREAD

**Issue by SamProtas** [fpco/lts-haskell#52]

**Comment by SamProtas** [comment]
I'm not sure what the standard approach is here, but my build matrix includes lts 6 and 7 as well. Do you typically add packages that build/pass tests to older lts versions?

If so, I suppose this can be a request to be added to those lts version as well. Otherwise, just 8.

**Comment by bergmark** [comment]
We can add them to older versions, but we build LTS 6 and 7 less often so it might take a while

**Comment by bergmark** [comment]
There are some bounds preventing us from adding triplesec to LTS 6, would you like to publish a new version that is compatible or should we skip adding it to LTS 6?

```
cryptonite-0.21 (Vincent Hanquez) is out of bounds for:
- [ ] triplesec-0.1.2.0 (>=0.23). No maintainer. @SamProtas. Used by: library
memory-0.13 (Vincent Hanquez) is out of bounds for:
- [ ] triplesec-0.1.2.0 (>=0.14.5). No maintainer. @SamProtas. Used by: library, test-suite
```

**Comment by bergmark** [comment]
LTS 8 also needs an older cryptonite:
```
cryptonite-0.21 (Vincent Hanquez @vincenthz) is out of bounds for:
- [ ] triplesec-0.1.2.0 (>=0.23). No maintainer. @SamProtas. Used by: library
```

**Comment by SamProtas** [comment]
Okay I'll close this issue then. TripleSec depends specifically on a block cipher added in cryptonite 0.23. TripleSec builds in nightly (it has latest cryptonite as well) so I'll wait for LTS 9 (or whenever cryptonite gets a bump). Thanks for letting me know.

**Comment by DanBurton** [comment]
We have allowed major bumps of cryptonite in the past within an lts major series, since Vincent is not fond of using minor release versions. We could consider bumping it again if we believe it to be backwards compatible.

**Comment by SamProtas** [comment]
@DanBurton at first glance (https://hackage.haskell.org/package/cryptonite-0.23/changelog) the 0.22 and 0.23 releases seem purely additive. I'm not sure exactly what would be involved in making the that determination for sure though (I haven't personally gone through all the diffs, and I'm not sure I'd trust me to make that call even if anyone would listen).

I'd be happy to help investigate if someone could provide a path forward, otherwise LTS 9 is fine.

**Comment by juhp** [comment]
Since triplesec is already in Stackage Nightly it should get into LTS 9 when it is released automatically
(assuming it doesn't fall out of Nightly for some reason).

**Comment by SamProtas** [comment]
Thanks for following up. I suppose we can close this issue unless it's helpful to keep around until lts 9 is out.
