### ISSUE TITLE
please (re-)add packages of relational-record to LTS-7

### ISSUE THREAD

**Issue by khibino** [fpco/lts-haskell#53]
I recognize that packages of relational-record are included from LTS-7.0 to LTS-7.20.
But I found that following packages (which are part of relational-record) are dropped from LTS-7.21.

* relational-query-HDBC
* persistable-types-HDBC-pg
* relational-record

Please re-add these package to LTS-7.

If it's alright with you, please tell me why these package are dropped?

**Comment by DanBurton** [comment]
There may be others that were dropped as well. Just eyeballing it, I see that `tries` was also dropped. It was presumably unintentional. @bergmark ?

**Comment by bergmark** [comment]
Yeah it must have been a mistake. I think I checked for accidental removals but I might have missed some still, I can re-run that script tonight.

**Comment by bergmark** [comment]
Back in LTS 7.22. Still missing hasql, I'll create a separate issue for that.
