### ISSUE TITLE
Snapshots contain versions not in all-cabal-hashes-commit

### ISSUE THREAD

**Issue by rimmington** [fpco/lts-haskell#55]
I'm examining the `all-cabal-hashes-commit` value in snapshots and noticed something odd: for at least LTS 8.10 and 8.13 (latest), the package `http-client-openssl` version `0.2.0.5` is specified in the build plan but does not exist in the ACH commit specified. I haven't done any kind of search for other missing package versions.

I'm not sure what guarantees Stackage provides regarding `all-cabal-hashes-commit`, but this makes it more difficult for me to determine the Hackage revision used in the build which I'd like to do for reproducing builds in Nix. I'm open to other ways to get revision information.

**Comment by snoyberg** [comment]
It was accidental that that field is still being populated, with the change to hackage-security it's no longer being used. Please instead use the `cabal-file-info.hashes` info instead. In particular, the `GitSHA1` value should play very nicely with the `all-cabal-hashes` repo.

**Comment by rimmington** [comment]
Great, thank you!

For reference, since I had to look it up: the `GitSHA1` hash is also precisely the way you refer to blobs in Git, so you can do `git show <hash>` to get the Cabal file. Also, the Hackage revision number (if > 0) is stored in the `x-revision` property in each Cabal file.
