### ISSUE TITLE
Add HLint to LTS-8.*

### ISSUE THREAD

**Issue by lwm** [fpco/lts-haskell#65]
I wasn't really keeping an eye, but shouldn't the new 2.x releases be in the latest LTS?

https://www.stackage.org/nightly-2017-07-17/package/hlint-2.0.9
https://www.stackage.org/lts-8.23/package/hlint-1.9.41

Pinging @ndmitchell

**Comment by ndmitchell** [comment]
No, it will only be in LTS 9. If you want to use the latest version of packages, use Nightly (I consider LTS useless for most purposes - but that's just my personal view).

**Comment by lwm** [comment]
:+1:
