### ISSUE TITLE
Add composable-associations and composable-associations-aeson to LTS 9

### ISSUE THREAD

**Issue by SamProtas** [fpco/lts-haskell#66]
It looks like my addition to stackage nightly _just_ missed the cutoff.

https://github.com/fpco/stackage/pull/2660

**Comment by SamProtas** [comment]
FYI looks like these packages made it into the latest nightly.

**Comment by DanBurton** [comment]
These are present in lts-9.2 (and beyond).

**Comment by SamProtas** [comment]
Thanks!
