### ISSUE TITLE
Upgrade to servant-docs-0.11

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#67]
0.10.0.1 is deprecated and identical to 0.11, https://github.com/fpco/stackage/issues/2664

**Comment by bergmark** [comment]
This is blocked by https://github.com/fpco/stackage/issues/2661

**Comment by DanBurton** [comment]
`servant-docs 0.11.*` is now present in lts-9.3 and beyond. See https://www.stackage.org/diff/lts-9.2/lts-9.3
