### ISSUE TITLE
LTS 9.5 mandated deprecated fgl 5.5.4.0

### ISSUE THREAD

**Issue by peti** [fpco/lts-haskell#70]
The latest Stackage LTS 9.x package set mandates use of `fgl-5.5.4.0`, but upstream has deprecated that version on Hackage.

Ping @ivan-m.

**Comment by ivan-m** [comment]
As I said in the other ticket: 5.5.4.0 mistakenly had a PVP-breaking change, so I deprecated it and released 5.6.0.0 instead.

**Comment by peti** [comment]
So the question is now what version should LTS 9.x use?

**Comment by bergmark** [comment]
The safe bet would be to downgrade to the version that was in 9.x before this release.

**Comment by peti** [comment]
Upgrading to 5.6.x is certainly going to be a bit of an effort because some packages (like graphviz) don't accept the newer version.

**Comment by ivan-m** [comment]
Yes, graphviz is on me.

I'll try and deal with that tonight.

**Comment by peti** [comment]
Ping? Will Stackage downgrade it's recommendation?

**Comment by ivan-m** [comment]
I would recommend downgrading back to 5.5.3.1 at this time (as part of fixing some parsing issues found in graphviz I've changed the API enough to warrant a major version bump there as well).

**Comment by bergmark** [comment]
Yes! coming up this weekend.

**Comment by bergmark** [comment]
Sorry for the delay... LTS 9.8 contains fgl-5.5.3.1.
