### ISSUE TITLE
The package identifiers were not found in my package indices

### ISSUE THREAD

**Issue by uruk1993** [fpco/lts-haskell#73]
When I was solving practice download from exercism.io, I met this problem. This problem occured recently, about two weeks ago everything worked fine. Following is the error message.

```
Downloaded lts-8.21 build plan.
Didn't see Agda-2.5.2@sha256:4db0b12bc07e72fe1b180acad2a0d59ac11d9a1d45698b46cede7b634fb6bfff,27524 in your package indices.
Updating and trying again.
Downloading package index from https://mirrors.ustc.edu.cn/hackage/00-index.tar.gz
No updates to your package index were found
Update complete
Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /home/uruk/.stack/build-plan/lts-8.21.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

The following package identifiers were not found in your indices: Agda-2.5.2@sha256:4db0b12bc07e72fe1b180acad2a0d59ac11d9a1d45698b46cede7b634fb6bfff,27524
The specified revision was not found.
Possible candidates: Agda-2.5.2@sha256:28af7449a60bce1d020020524e72779415d04dd2a83dee57ec62eff484834282, Agda-2.5.2@sha256:16152f1ea7f461dfc48aee61a75a7f1018832e9bcbcae45eba3a7d08ff1f28c9.
```

**Comment by snoyberg** [comment]
What version of Stack are you using, and how did you install it? You can check the former with `stack --version`.

**Comment by uruk1993** [comment]
sorry, I missed this crucial infomation, my stack version is `Version 1.5.1 x86_64` and My OS is archlinux.

**Comment by snoyberg** [comment]
Is that the full output of `stack --version`, or does it include a Git SHA?

**Comment by uruk1993** [comment]
Actually the full output of `stack --version` is following and there is no Git SHA
stack --version
Version 1.5.1 x86_64
Compiled with:
- Cabal-2.0.0.2
- Glob-0.7.14
- HUnit-1.6.0.0
- MonadRandom-0.5.1
- QuickCheck-2.10.1
- StateVar-1.1.0.4
- aeson-1.2.3.0
- aeson-compat-0.3.7.1
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8.1
- array-0.5.2.0
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.2.0
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-4.10.0.0
- base-compat-0.9.3
- base-orphans-0.6
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- basement-0.0.3
- bifunctors-5.4.2
- binary-0.8.5.1
- bindings-uname-0.1
- bitarray-0.0.1.1
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteable-0.1.1
- bytestring-0.10.8.2
- call-stack-0.1.0
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- clock-0.7.2
- comonad-5.0.2
- conduit-1.2.12.1
- conduit-extra-1.1.17
- connection-0.2.8
- containers-0.5.10.2
- contravariant-1.4
- cookie-0.4.2.1
- cryptohash-0.11.9
- cryptohash-sha256-0.11.100.1
- cryptonite-0.24
- cryptonite-conduit-0.2.0
- data-default-class-0.1.2.0
- deepseq-1.4.3.0
- digest-0.0.1.2
- directory-1.3.0.2
- distributive-0.5.3
- dlist-0.8.0.3
- easy-file-0.2.1
- echo-0.1.3
- ed25519-0.0.5.0
- either-4.4.1.1
- exceptions-0.8.3
- extra-1.6
- fast-logger-2.4.10
- file-embed-0.0.10.1
- filelock-0.1.1.2
- filepath-1.4.1.2
- foundation-0.0.16
- free-4.12.4
- fsnotify-0.2.1.1
- generic-deriving-1.11.2
- ghc-boot-th-8.2.1
- ghc-prim-0.5.1.0
- gitrev-1.3.1
- hackage-security-0.5.2.2
- hashable-1.2.6.1
- hastache-0.6.1
- hinotify-0.3.9
- hourglass-0.2.10
- hpack-0.18.1
- hpc-0.6.0.3
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- hspec-smallcheck-0.4.2
- http-api-data-0.3.7.1
- http-client-0.5.7.0
- http-client-tls-0.3.5.1
- http-conduit-2.2.3.2
- http-types-0.9.1
- ieee754-0.8.0
- integer-gmp-1.0.1.0
- integer-logarithms-1.0.2
- lifted-base-0.2.3.11
- logict-0.6.0.2
- memory-0.14.8
- microlens-0.4.8.1
- microlens-mtl-0.1.11.0
- microlens-th-0.4.1.1
- mime-types-0.1.0.7
- mintty-0.1.1
- mmorph-1.1.0
- monad-control-1.0.2.2
- monad-logger-0.3.25.1
- monad-loops-0.4.3
- mono-traversable-1.0.2.1
- mtl-2.2.1
- network-2.6.3.2
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.14.0.0
- optparse-simple-0.0.3
- parsec-3.1.11
- path-0.6.1
- path-io-1.3.3
- path-pieces-0.2.1
- pem-0.2.2
- persistent-2.7.0
- persistent-sqlite-2.6.2
- persistent-template-2.5.2
- pid1-0.1.2.0
- prelude-extras-0.4.0.3
- pretty-1.1.3.3
- primitive-0.6.2.0
- process-1.6.1.0
- profunctors-5.2.1
- project-template-0.2.0
- quickcheck-io-0.2.0
- random-1.1
- regex-applicative-0.3.3
- regex-applicative-text-0.1.0.1
- resource-pool-0.2.3.2
- resourcet-1.1.9
- retry-0.7.4.2
- rts-1.0
- safe-0.3.15
- scientific-0.3.5.2
- semigroupoids-5.2.1
- semigroups-0.18.3
- setenv-0.1.1.3
- silently-1.2.5
- smallcheck-1.1.2
- socks-0.5.5
- split-0.2.3.2
- stm-2.4.4.1
- stm-chans-3.0.0.4
- store-0.4.3.2
- store-core-0.4.1
- streaming-commons-0.1.18
- syb-0.7
- tagged-0.8.5
- tar-0.5.0.3
- template-haskell-2.12.0.0
- temporary-1.2.1.1
- text-1.2.2.2
- text-metrics-0.3.0
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.3.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- th-orphans-0.13.4
- th-reify-many-0.1.8
- th-utilities-0.2.0.1
- time-1.8.0.2
- time-locale-compat-0.1.1.3
- tls-1.4.0
- transformers-0.5.2.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unicode-transforms-0.3.3
- unix-2.7.2.2
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unliftio-0.1.0.0
- unliftio-core-0.1.0.0
- unordered-containers-0.2.8.0
- uri-bytestring-0.2.3.3
- uuid-types-1.0.3
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- void-0.7.2
- x509-1.7.2
- x509-store-1.6.5
- x509-system-1.6.6
- x509-validation-1.6.9
- yaml-0.8.23.3
- zip-archive-0.3.1.1
- zlib-0.6.1.2

**Comment by snoyberg** [comment]
I believe this output means that Arch Linux is shipping non-standard executables which have been built with cabal. (The building with cabal part isn't the problem, it's just what tells me that it's a non-standard executable.) The fact that it's using Cabal-2.0.0.2 (and that it's Arch Linux) tells me it's using a non-officially-released version of Stack.

Recommendation: download the `stack` executable from the releases on Github and try again. Or alternatively: play with the `stack upgrade` feature and maybe even `stack upgrade --git` so that we at least know which Git commit you're on.

In addition: your initial bug report gives an error message, but no repro steps. If the above does not help, please provide a minimal repro (e.g., "I have this `stack.yaml` file and I ran these commands).

**Comment by uruk1993** [comment]
Thank you for your advise. You are right, when download an officially-released version of Stack, everything works well.

**Comment by snoyberg** [comment]
No problem. If you have a chance to test with a build of `stack` from master (via `stack upgrade --git`), it would be really nice to know if the problem persists.

**Comment by uruk1993** [comment]
After remove the archlinux version of  `stack`,  I use the  officially-released executable executed the command `stack upgrade --git`, and the same problem appeared. The problem stack version is `Version 1.5.1, Git revision c8c74651696c8678a8dfebd3948b06a35015bd1a x86_64 hpack-0.18.1`

**Comment by uruk1993** [comment]
The content of my stack file is just `resolver: lts-8.21`

**Comment by snoyberg** [comment]
I think you have some local configuration you forgot to mention:

```
Downloading package index from https://mirrors.ustc.edu.cn/hackage/00-index.tar.gz
```

You need to point at the 01-index.tar.gz file.
