### ISSUE TITLE
Updating package index Hackage fail

### ISSUE THREAD

**Issue by suxiang198** [fpco/lts-haskell#79]
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
Blocked here and no longer continue

**Comment by snoyberg** [comment]
This most likely was just a slow download, the index is unfortunately quite large. How long did you give it before killing the process?

**Comment by mgsloan** [comment]
Yep, should have a progress indication, which is tracked by https://github.com/commercialhaskell/stack/issues/2622

**Comment by suxiang198** [comment]
@snoyberg Waited for about 4 hours before killing the process. I tried this process next day and it worked.
