### ISSUE TITLE
stack install fail

### ISSUE THREAD

**Issue by suxiang198** [fpco/lts-haskell#80]
stack install
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                Downloading root                                                                Unable to load cabal files for snapshot                                                                                                                         ----                                                                            Deleting cached snapshot file: /root/.stack/build-plan/lts-9.13.yaml            Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new                                  ----  

Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...SomeRemoteError (HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("Cache-Control","no-transform")]
  path                 = "/hackage.fpcomplete.com/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout)

**Comment by snoyberg** [comment]
Can you try running stack update by itself?

**Comment by suxiang198** [comment]
Thx, run 'stack update' can solve this. Maybe it's because the network speed is worse, I have to try 'stack install' a few more times to solve the problem when connection timeout occurs.
