### ISSUE TITLE
add ticket template like Stackage Nightly PR template?

### ISSUE THREAD

**Issue by juhp** [fpco/lts-haskell#83]
cf https://github.com/fpco/stackage/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by juhp** [comment]
Except we don't use PRs...  Is there a ticket template file?

**Comment by juhp** [comment]
- [ ] specified LTS version
- [ ] tested build with LTS version

and some explanation too probably...

**Comment by DanBurton** [comment]
There is an issue template file. See https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by lwm** [comment]
+1

**Comment by juhp** [comment]
How about commit 8962b77 as a starting point?

However we sometimes get ticket for problems other than adding packages...
Maybe more text is required

**Comment by juhp** [comment]
Closing this out then
