### ISSUE TITLE
Include aeson-yak in LTS-10.1

### ISSUE THREAD

**Issue by tejon** [fpco/lts-haskell#86]
Hi! If possible, I'd like to get the `aeson-yak` package included in lts-10.1. I've verified that the latest version (0.1.1.3) builds cleanly with `stack build --resolver lts-10.0 --test --bench --haddock`.

My PR for nightly inclusion is here: https://github.com/fpco/stackage/pull/3127

**Comment by lwm** [comment]
👍

**Comment by snoyberg** [comment]
Done https://www.stackage.org/lts-10.1/package/aeson-yak-0.1.1.3
