### ISSUE TITLE
Add Cabal-2.0.1.1 to LTS-10.2

### ISSUE THREAD

**Issue by ahri** [fpco/lts-haskell#88]
Missing package when using stack 1.6.3:

    The following package identifiers were not found in your indices: Cabal-2.0.1.1@sha256:69097de1c42e3626a7f36db4ce48eea0342783e037b1fd4f014f0d79d8ef8a4c,12886
    Possible candidates: Cabal-2.0.0.2.

Note: migrating from lts-9.10, no options set in `stack.yaml` except for resolver.

build-depends in cabal file:

    build-depends:       base >= 4.7 && < 5
                         , time >= 1.6.0.1 && < 1.7
                         , hspec
                         , QuickCheck

**Comment by ahri** [comment]
Removing the version requirements on time seems to have solved it for me.

On Windows for the same project this does not seem to be the case, which doesn't make sense, so I've removed my cache and am rebuilding from scratch to see if that helps.

**Comment by ahri** [comment]
Removing my cache on Windows solved the problem.

I'm not sure where to go with this, then. I assume it was merely due to my config/environment, so feel free to close!

**Comment by bergmark** [comment]
Maybe `stack update` would have resolved it as well?
