### ISSUE TITLE
Ubuntu PPA for LTS Haskell libraries

### ISSUE THREAD

**Issue by snoyberg** [fpco/lts-haskell#9]
This would be useful for end users, and especially useful for Travis builds (as @ndmitchell mentioned elsewhere). Details to be discussed.

**Comment by snoyberg** [comment]
Hopefully helpful list of Debian/Ubuntu system library dependencies:

https://github.com/fpco/stackage/blob/master/debian-bootstrap.sh

**Comment by snoyberg** [comment]
To be followed up with the Debian guys.

**Comment by dysinger** [comment]
Should we close this? I wasn't able to make the 1.2GB debian package useful on Travis because instance store EC2 root filesystem is only 10GB total. After expansion & shuffling files by dpkg in preparation for install, the filesystem runs out of space.

**Comment by ketzacoatl** [comment]
Is the root filesystem limit imposed by travis?
