### ISSUE TITLE
add bhoogle to lts-10

### ISSUE THREAD

**Issue by andrevdm** [fpco/lts-haskell#93]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] run `stack --resolver lts-10.3 build --haddock --test --bench --no-run-benchmarks`

Add
 - bhoogle

**Comment by snoyberg** [comment]
Added in LTS-10.5 https://www.stackage.org/lts-10.5/package/bhoogle-0.1.2.5
